"use client";

import { useEffect, useState, useMemo } from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Download, FileText, Search, ShieldCheck, HelpCircle } from "lucide-react";

interface Resource {
  id: string;
  title: string;
  description: string;
  type: string;
  fileUrl: string;
  category: string;
  createdAt: string;
}

const RESOURCE_TYPES = ["All", "Template", "Checklist", "Spreadsheet"];

export default function Resources() {
  const [resources, setResources] = useState<Resource[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedType, setSelectedType] = useState("All");

  useEffect(() => {
    async function loadResources() {
      try {
        const res = await fetch("/api/resources");
        if (res.ok) {
          const data = await res.json();
          setResources(data.resources);
        }
      } catch (error) {
        console.error("Failed to fetch resources:", error);
      } finally {
        setLoading(false);
      }
    }
    loadResources();
  }, []);

  const filteredResources = useMemo(() => {
    return resources.filter((res) => {
      const matchesType =
        selectedType === "All" || res.type.toLowerCase() === selectedType.toLowerCase();

      const tokens = searchQuery.toLowerCase().trim().split(/\s+/);
      const matchesSearch = tokens.every(
        (token) =>
          res.title.toLowerCase().includes(token) ||
          res.description.toLowerCase().includes(token) ||
          res.category.toLowerCase().includes(token)
      );

      return matchesType && matchesSearch;
    });
  }, [resources, selectedType, searchQuery]);

  // Performs a mock download by writing a descriptive contract/checklist txt file on the fly
  const handleDownload = (resource: Resource) => {
    const fileContent = `========================================================================
STARTUP NAVIGATOR CURATED RESOURCE PACK
========================================================================
Resource Title  : ${resource.title}
Category        : ${resource.category}
Document Type   : ${resource.type}
Creation Date   : ${new Date(resource.createdAt).toLocaleDateString()}

DESCRIPTION:
${resource.description}

------------------------------------------------------------------------
LEGAL DISCLAIMER:
This document is a mock template provided for reference and educational
purposes. It does not constitute formal legal advice. Startup founders 
should consult qualified legal counsel and accounting specialists before
executing documents of corporate formation, equity, or fundraising.

------------------------------------------------------------------------
STANDARD PROVISIONS & CLAUSES:
1. FORMATION ACTIONS
   Subject to Delaware General Corporation Law, the incorporating officers
   hereby establish corporate structures to assign and partition outstanding
   shares among founders.
   
2. FOUNDER VESTING SCHEDULE
   Outstanding shares shall vest over a standard 4-year term, subject to
   a 1-year cliff. Departure prior to 12 months forfeits 100% of the assigned
   grant.

3. INTELLECTUAL PROPERTY ASSIGNMENT
   All inventions, patents, source code, repositories, designs, and marks
   conceived during corporate operations are hereby transferred in perpetuity
   to the corporation.

========================================================================
Generated by Startup Navigator — https://startup-navigator.vercel.app
========================================================================
`;

    const blob = new Blob([fileContent], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    
    // Clean filename
    const safeName = resource.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .substring(0, 30);
    link.download = `sn_${safeName}_template.txt`;
    
    document.body.appendChild(link);
    link.click();
    
    // Cleanup
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <>
      <Navbar />

      <main className="flex-grow max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Page Header */}
        <div className="text-center mb-12">
          <h1 className="text-3xl sm:text-4xl font-display font-extrabold text-white">
            Startup <span className="text-gradient">Resource Library</span>
          </h1>
          <p className="mt-2 text-sm sm:text-base text-slate-400 max-w-2xl mx-auto">
            Download standard agreements, financial sheets, and legal frameworks to streamline your admin workflows.
          </p>
        </div>

        {/* Search and Filters */}
        <div className="flex flex-col md:flex-row gap-4 justify-between items-center mb-10 bg-slate-900/40 p-4 rounded-2xl border border-slate-800/60 glassmorphism">
          {/* Search Input */}
          <div className="relative w-full md:max-w-md">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-500" />
            <input
              type="text"
              placeholder="Search templates, worksheets..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-10 pr-4 py-2.5 bg-slate-950 border border-slate-800 rounded-xl text-slate-100 placeholder-slate-500 focus:outline-none focus:border-indigo-500 text-sm transition"
            />
          </div>

          {/* Type Filter Buttons */}
          <div className="flex bg-slate-950 p-1 rounded-xl border border-slate-800/80 w-full md:w-auto overflow-x-auto">
            {RESOURCE_TYPES.map((type) => (
              <button
                key={type}
                onClick={() => setSelectedType(type)}
                className={`flex-grow md:flex-grow-0 px-4 py-1.5 rounded-lg text-xs font-medium transition cursor-pointer ${
                  selectedType === type
                    ? "bg-indigo-600 text-white font-semibold shadow"
                    : "text-slate-400 hover:text-white"
                }`}
              >
                {type}s
              </button>
            ))}
          </div>
        </div>

        {/* Resources Grid */}
        {loading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {[1, 2, 3, 4].map((n) => (
              <div
                key={n}
                className="h-48 rounded-2xl bg-slate-900/30 border border-slate-800/50 animate-pulse"
              ></div>
            ))}
          </div>
        ) : filteredResources.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {filteredResources.map((res) => (
              <div
                key={res.id}
                className="flex flex-col p-6 rounded-2xl glassmorphism-card bg-slate-950/20 text-left border border-slate-900 hover:border-slate-800"
              >
                {/* Header: Document Type badge */}
                <div className="flex items-center justify-between mb-4">
                  <span className="inline-flex items-center space-x-1.5 px-2.5 py-1 rounded-md bg-slate-900 border border-slate-800 text-[10px] font-bold text-slate-400 uppercase tracking-wider">
                    <FileText className="h-3 w-3 text-indigo-400" />
                    <span>{res.type}</span>
                  </span>
                  <span className="text-[10px] text-slate-500 font-medium">
                    {res.category}
                  </span>
                </div>

                {/* Title */}
                <h3 className="text-base font-semibold text-white leading-snug line-clamp-1">
                  {res.title}
                </h3>

                {/* Description */}
                <p className="mt-2 text-xs sm:text-sm text-slate-400 leading-relaxed line-clamp-3 flex-grow">
                  {res.description}
                </p>

                {/* Footer and Download Trigger */}
                <div className="mt-6 pt-4 border-t border-slate-900/80 flex items-center justify-between">
                  <div className="flex items-center space-x-1 text-[10px] text-emerald-400 font-medium">
                    <ShieldCheck className="h-3.5 w-3.5" />
                    <span>Verified safe</span>
                  </div>

                  <button
                    onClick={() => handleDownload(res)}
                    className="flex items-center space-x-1.5 px-3.5 py-2 bg-indigo-650 hover:bg-indigo-600 border border-indigo-700 text-white rounded-lg text-xs font-semibold cursor-pointer transition btn-gradient"
                  >
                    <Download className="h-3.5 w-3.5" />
                    <span>Download</span>
                  </button>
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="text-center py-20 bg-slate-900/10 border border-slate-800/40 rounded-2xl p-8">
            <HelpCircle className="h-10 w-10 text-slate-600 mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-white">No resources found</h3>
            <p className="text-sm text-slate-400 mt-2">
              We couldn&apos;t find any resources matching your current search parameters.
            </p>
          </div>
        )}
      </main>

      <Footer />
    </>
  );
}
